worked on bash seed script

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,16 +1,21 @@
 #! /usr/bin/bash
+set -e # stop if it fails at any point
 
 if [ -z "$1" ]; then
     echo "No Table name argument is supplied."
+    exit 1;
+fi
+TABLE_NAME=$1
+
+if [ "$2" == "prod" ]; then
     ENDPOINT_URL = ""
 else
-    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
+    ENDPOINT_URL="http://localhost:8000"
 fi
 
-if [ "$1" == "prod" ]; then
-    ENDPOINT_URL = ""
-else
-    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
-fi
+echo "table name : $TABLE_NAME"
 
-aws dynamodb delete-table --table-name Music
+aws dynamodb delete-table \
+  --endpoint-url $ENDPOINT_URL \
+  --table-name $TABLE_NAME
+  
